name: Build and Mirror Dependencies

on:
  push:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MAVEN_REPO_URL: https://maven.pkg.github.com/${{ github.repository }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configure settings.xml for GitHub Packages
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GITHUB_TOKEN }}</password>
              </server>
            </servers>
            <profiles>
              <profile>
                <id>github</id>
                <repositories>
                  <repository>
                    <id>central</id>
                    <url>https://repo.maven.apache.org/maven2</url>
                  </repository>
                  <repository>
                    <id>github</id>
                    <url>${{ env.MAVEN_REPO_URL }}</url>
                  </repository>
                </repositories>
              </profile>
            </profiles>
            <activeProfiles>
              <activeProfile>github</activeProfile>
            </activeProfiles>
          </settings>
          EOF

      - name: Resolve all dependencies (and copy them)
        run: |
          mkdir -p mirrored-deps
          mvn dependency:copy-dependencies -DoutputDirectory=mirrored-deps

      - name: Deploy dependencies to GitHub Packages
        run: |
          for jar in mirrored-deps/*.jar; do
            filename=$(basename "$jar")
            
            # Better parsing of artifact name and version
            if [[ "$filename" =~ ^(.+)-([0-9]+\.[0-9]+.*?)\.jar$ ]]; then
              name="${BASH_REMATCH[1]}"
              version="${BASH_REMATCH[2]}"
            else
              echo "Skipping $filename - cannot parse name and version"
              continue
            fi

            # Skip your own artifact if it's in the list
            if [[ "$name" == "my-app" ]]; then
              continue
            fi

            echo "Processing: $name version $version"

            # Check if artifact already exists
            STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "${{ env.MAVEN_REPO_URL }}/vinodhdevaarul/thirdparty/$name/$version/$name-$version.jar")

            if [[ "$STATUS_CODE" == "200" ]]; then
              echo "Artifact $name:$version already exists, skipping..."
              continue
            fi

            # Deploy the artifact
            echo "Deploying $name:$version..."
            if ! mvn deploy:deploy-file \
              -Dfile="$jar" \
              -DgroupId="vinodhdevaarul.thirdparty" \
              -DartifactId="$name" \
              -Dversion="$version" \
              -Dpackaging=jar \
              -DrepositoryId=github \
              -Durl=${{ env.MAVEN_REPO_URL }} \
              -DgeneratePom=true; then
              echo "Failed to deploy $name:$version, but continuing..."
            fi
          done

      - name: Build project
        run: mvn clean install

      - name: Deploy your own artifact
        run: |
          mvn deploy -DrepositoryId=github -Durl=${{ env.MAVEN_REPO_URL }}